version: '2'
services:
  docker-pde: 
    build: .
    image: zojeda/docker-pde
    ports:
      - "8080"
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"      
      - ".:/dockerPDE"
  docker-pde-proxy:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - "./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    
      