version: '2'
services:
  docker-pde: 
    build: .
    image: zojeda/docker-pde
    ports:
      - "8080"
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"      
      - ".:/dockerPDE"
  docker-pde-workspace-watcher: 
    image: zojeda/docker-pde
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - haconfig:/haproxy
      - ".:/dockerPDE"
    working_dir: /dockerPDE/dockerode-bars
    command: "ts-node ./src/DockerodeBarsCli.ts 
               -s ../services/haproxy/docker-pde-haproxy.hbs
               -o /haproxy/haproxy.cfg
               -w 
               -c com.docker.compose.service=docker-pde-proxy"      
  docker-pde-proxy:
    image: haproxy
    ports:
      - "8080:8080"
    depends_on: 
      - docker-pde-workspace-watcher
    volumes:
      - haconfig:/usr/local/etc/haproxy/:ro
          

volumes:
  haconfig: {}